name: crm-base-staging

services:
  db:
    env_file:
      - ./env/staging/.env.db

  backend:
    image: ghcr.io/jackdevtech455/crm_base-backend:latest
    env_file:
      - ./env/staging/.env.backend
    expose:
      - "8000"
    command: uv run uvicorn app.main:app --host 0.0.0.0 --port 8000
    networks:
      - proxy

  frontend:
    image: ghcr.io/jackdevtech455/crm_base-frontend:latest
    expose:
      - "5173"
    env_file:
      - ./env/staging/.env.frontend
    command: pnpm dev --host 0.0.0.0
    networks:
      - proxy

volumes:
  postgres_data:

networks:
  proxy:
    external: true
