services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app

  backend:
    restart: unless-stopped
    networks:
      - app
    depends_on:
      - db


  frontend:
    restart: unless-stopped
    networks:
      - app
    depends_on:
      - backend

networks:
  app:
