services:
  db:
    env_file:
      - .env.staging  # TODO make crash if not found
    networks:
      - internal

  backend:
    image: ghcr.io/jackdevtech455/crm_base-backend:latest
    env_file:
      - .env.staging
    expose:
      - "8000"
    command: uv run uvicorn app.main:app --host 0.0.0.0 --port 8000
    networks:
      - internal
      - proxy

  frontend:
    image: ghcr.io/jackdevtech455/crm_base-frontend:latest
    expose:
      - "5173"
    env_file:
      - .env.staging
    command: pnpm dev --host 0.0.0.0
    networks:
      - proxy
    depends_on:
      - backend

volumes:
  postgres_data:

networks:
  internal:
    internal: true
  proxy:
    external: true
